# =================================================
# 1?? Backoffice credentials
# =================================================
backoffice.user.email=mariem.elhouche-ext@noveocare.com
backoffice.user.password=Noveocare.2026**


# URL de l'application Back-Office
backoffice.url=https://stg-bo.noveocare.com/login
# =================================================
# 3?? API / Microservices
# =================================================
self.healing.api.url=https://epigastric-troy-calculating.ngrok-free.dev/heal
# Timeout en secondes pour les appels API
self.healing.api.timeout=10
self.healing.enabled=false
