services:
  runner:
    build: .
    container_name: ai-test-runner
    restart: unless-stopped
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - REPO_URL=${REPO_URL:-https://github.com/Mariem-Elhouche/ai_test_automation_framework}
      - RUNNER_NAME=${RUNNER_NAME:-docker-runner}
    volumes:
      - m2_cache:/home/runner/.m2
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  m2_cache:
